# Generated by Django 4.2.7 on 2025-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChitFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('permanentAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('temporaryAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('juniorAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('villageContribution', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('otherContributions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inputGrandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grandTotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amountSpent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
