# Generated by Django 4.2.7 on 2025-12-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leaderboard_visible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Quiz Settings',
            },
        ),
    ]
