# Generated by Django 4.2.7 on 2025-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juniormember',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juniormember',
            name='amountInvested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='juniormember',
            name='amountPaidThisYear',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='juniormember',
            name='profilePic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='amountInvested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='amountPaidThisYear',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='permanentmember',
            name='profilePic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='amountInvested',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='amountPaidThisYear',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='temporarymember',
            name='profilePic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juniormember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juniormember',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juniormember',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='permanentmember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permanentmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='permanentmember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temporarymember',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
